version: 1.10.{build}

image: Visual Studio 2022

clone_folder: c:\projects\SeriousEngine

clone_depth: 1

branches:
  only:
    - master

configuration:
  - Release

before_build:
  - cd c:\projects\SeriousEngine\
  - git submodule -q update --init
  - cd Sources
  - GenerateAssimpSLN.bat
  - cd c:\projects\SeriousEngine\Sources
  - GenerateQtWinMigrateSLN.bat
  - cd c:\projects\SeriousEngine\Sources
  - GenerateSeriousEngineCppAPI.bat
  - cd c:\projects\SeriousEngine\Sources
  - GenerateCrashRptSLN.bat

build:
  parallel: true
  project: Sources\All.sln
  verbosity: normal

after_build:
  - cd c:\projects\SeriousEngine\
  - mkdir deploy
  - xcopy /E /I Bin deploy\Bin
  - xcopy /E /I Licenses deploy\Licenses
  - xcopy /I SE1_10_AdditionalData.gro deploy\
  - mkdir deploy_pdb
  - xcopy /I Sources\EngineGui\Release\EngineEX.pdb deploy_pdb\
  - xcopy /I Sources\Modeler\Release\SeriousModelerEX.pdb deploy_pdb\
  - xcopy /I Sources\WorldEditor\Release\SeriousEditorEX.pdb deploy_pdb\

artifacts:
  - path: .\deploy
    name: SeriousEditorEX-$(appveyor_build_version)
    type: zip
    
  - path: .\deploy_pdb
    name: SeriousEditorEX_debug_symbols-$(appveyor_build_version)
    type: zip

deploy:
  description: SeriousEditorEX-$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: El4m3Fh87K1KfMgnmCfo4hih09KHfZDUojWI9Sb9Sd0kfYvrrfxDQ77I/5Sg03Zd5Rh72j6hcO5kFSFc5AP4jHug7+1rugWcTSb/U+gIqbp97eXEOErjOfLStj+9DKNs
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
