DLLFUNCTION(void, glActiveTexture, (GLenum texture));
DLLFUNCTION(void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels));
DLLFUNCTION(void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
DLLFUNCTION(GLboolean, glIsEnabled, (GLenum cap));
DLLFUNCTION(void, glPointSize, (GLfloat size));
DLLFUNCTION(void, glClearColor, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
DLLFUNCTION(void, glClear, (GLbitfield mask));
DLLFUNCTION(void, glClearDepth, (GLdouble depth));
DLLFUNCTION(void, glClearStencil, (GLint s));
DLLFUNCTION(GLuint, glCreateShader, (GLenum type));
DLLFUNCTION(void, glShaderSource, (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length));
DLLFUNCTION(void, glCompileShader, (GLuint shader));
DLLFUNCTION(void, glGetShaderiv, (GLuint shader, GLenum pname, GLint *params));
DLLFUNCTION(void, glGetShaderInfoLog, (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog));
DLLFUNCTION(void, glUseProgram, (GLuint program));
DLLFUNCTION(GLuint, glCreateProgram, (void));
DLLFUNCTION(void, glAttachShader, (GLuint program, GLuint shader));
DLLFUNCTION(void, glLinkProgram, (GLuint program));
DLLFUNCTION(GLint, glGetUniformLocation, (GLuint program, const GLchar *name));
DLLFUNCTION(void, glUniform1i, (GLint location, GLint v0));
DLLFUNCTION(void, glUniform1f, (GLint location, GLfloat v0));
DLLFUNCTION(void, glUniform2f, (GLint location, GLfloat v0, GLfloat v1));
DLLFUNCTION(void, glUniform3f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2));
DLLFUNCTION(void, glUniform4f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3));
DLLFUNCTION(void, glUniformMatrix3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value));
DLLFUNCTION(void, glUniformMatrix4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value));
DLLFUNCTION(GLint, glGetAttribLocation, (GLuint program, const GLchar *name));
DLLFUNCTION(void, glTexParameteri, (GLenum target, GLenum pname, GLint param));
DLLFUNCTION(void, glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels));
DLLFUNCTION(void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels));
DLLFUNCTION(void, glBindTexture, (GLenum target, GLuint texture));
DLLFUNCTION(void, glGetTexLevelParameteriv, (GLenum target, GLint level, GLenum pname, GLint *params));
DLLFUNCTION(void, glEnable, (GLenum cap));
DLLFUNCTION(void, glDisable, (GLenum cap));
DLLFUNCTION(void, glFrontFace, (GLenum mode));
DLLFUNCTION(void, glDepthMask, (GLboolean flag));
DLLFUNCTION(void, glDepthFunc, (GLenum func));
DLLFUNCTION(void, glBlendFunc, (GLenum sfactor, GLenum dfactor));
DLLFUNCTION(void, glDepthRange, (GLdouble n, GLdouble f));
DLLFUNCTION(void, glDrawBuffer, (GLenum buf));
DLLFUNCTION(void, glPixelStorei, (GLenum pname, GLint param));
DLLFUNCTION(const GLubyte *, glGetString, (GLenum name));
DLLFUNCTION(void, glGetIntegerv, (GLenum pname, GLint *data));
DLLFUNCTION(void, glGetFloatv, (GLenum pname, GLfloat *data));
DLLFUNCTION(GLenum, glGetError, (void));
DLLFUNCTION(void, glGenTextures, (GLsizei n, GLuint *textures));
DLLFUNCTION(void, glDeleteTextures, (GLsizei n, const GLuint *textures));
